### ISSUE TITLE
PodIntents fails when specifying resource limits

### ISSUE THREAD

**Issue by mhoshi-vm** [vmware-tanzu/cartographer-conventions#154]
**Bug description**

When deploying the following podintent

```
apiVersion: conventions.apps.tanzu.vmware.com/v1alpha1
kind: PodIntent
metadata:
  name: podintent-test
spec:
  template:
    metadata:
      annotations:
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
    spec:
      containers:
        - image: ghcr.io/nginx-proxy/nginx-proxy:latest
          name: workload
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
```

the podintent fails immediately with the following status

```
status:
  conditions:
  - lastTransitionTime: "2022-07-05T21:31:06Z"
    message: 'failed to apply convention from source covention-via-spring: quantities
      must match the regular expression ''^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'''
    reason: ConventionsApplied
    status: "False"
    type: ConventionsApplied
  - lastTransitionTime: "2022-07-05T21:31:06Z"
    message: 'failed to apply convention from source covention-via-spring: quantities
      must match the regular expression ''^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'''
    reason: ConventionsApplied
    status: "False"
    type: Ready
  observedGeneration: 1
```

The issue does not occur when the resource limit is removed.

**Expected behavior**

PodIntent should understand the resource limit

**Steps to reproduce the bug**

Deploy the above podintent

**Version** (Tanzu Application Platform, K8s the controller is installed on)

TAP 1.1.2

**Environment where the bug was observed (cloud, OS, etc)**

TKG 

**Relevant Debug Output (Logs, etc)**

I see the following in the convention controller pod

```
{"level":"error","ts":"2022-07-05T21:34:01.432287895Z","logger":"controllers.PodIntent.PodIntent.ApplyConventions","msg":"failed to apply convention","Convention":{"Name":"covention-via-spring","Selectors":null,"Priority":"Early","ClientConfig":{"url":"https://my-convention-default.demo.cl01.lespaulstudioplus.info/convention"}},"error":"quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","stacktrace":"github.com/vmware-tanzu/convention-controller/pkg/controllers.ApplyConventionsReconciler.func1\n\tgithub.com/vmware-tanzu/convention-controller/pkg/controllers/podintent_reconciler.go:277\nreflect.Value.call\n\treflect/value.go:556\nreflect.Value.Call\n\treflect/value.go:339\ngithub.com/vmware-labs/reconciler-runtime/reconcilers.(*SyncReconciler).sync\n\tgithub.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:324\ngithub.com/vmware-labs/reconciler-runtime/reconcilers.(*SyncReconciler).Reconcile\n\tgithub.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:313\ngithub.com/vmware-labs/reconciler-runtime/reconcilers.Sequence.Reconcile\n\tgithub.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:852\ngithub.com/vmware-labs/reconciler-runtime/reconcilers.(*ParentReconciler).reconcile\n\tgithub.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:149\ngithub.com/vmware-labs/reconciler-runtime/reconcilers.(*ParentReconciler).Reconcile\n\tgithub.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:120\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```
