### ISSUE TITLE
Controller manager pod crashed with OOMKilled - AKS Cluster

### ISSUE THREAD

**Issue by katmutua** [vmware-tanzu/cartographer-conventions#257]
### Bug description

During a TAP **1.3.0** upgrade we observed that the controller manager  pod was not able to get to a running state and the pod status condition  was - **OOMkilled** .

We also observed a huge number of secrets across namespaces. After editing the deployment  to  modify the memory limits  from `memory: 256Mi` to limits: `memory: 512Mi` the pod was  temporarily revived.

### Expected behavior
The controller manager should not crash.

### Relevant Logs

```yaml
lastState:
      terminated:
        containerID: containerd://5cd68517d42c9220ee08dfe0852aadde3914b06daf6d30e3516d16faf8c71fe3
        exitCode: 137
        finishedAt: "2022-10-13T21:01:34Z"
        reason: OOMKilled
        startedAt: "2022-10-13T21:01:00Z"
    name: manager
    ready: false
    restartCount: 52
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=manager pod=cartographer-conventions-controller-manager-85b5f66c6f-q58lm_cartographer-system(b8e0254e-b7a6-445a-af70-37d026c5eff1)
        reason: CrashLoopBackOff
```

**Steps to reproduce the bug**
Deploy TAP 1.2.x in a cluster with a substantial load and upgrade the vesion to TAP 1.3.0 

**Version** (Tanzu Application Platform, K8s the controller is installed on): Upgrading to v1.3.0 
**Environment where the bug was observed (cloud, OS, etc)**: AKS

**NOTE**:  A separate issue to address the need to create a YTT overlay to configure resource limits added here: [Issue 256] (https://github.com/vmware-tanzu/cartographer-conventions/issues/256)
