### ISSUE TITLE
Spring Boot Conventions: Wrong Graceful Shutdown Convention

### ISSUE THREAD

**Issue by ThomasVitale** [vmware-tanzu/cartographer-conventions#294]
**Bug description**

The Spring Boot Conventions sample includes a few different conventions including the configuration for the graceful shutdown. The `server.shutdown=graceful` property is never set. Also, the grace period is configured via the `server.shutdown.grace-period` property, which was introduced in Spring Boot 2.3 M2 (see [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3.0-M3-Release-Notes)) but that has been very soon replaced by the `server.lifecycle.timeout-per-shutdown-phase` property in the final 2.3 release (see [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes)). That means the grace period is actually never configured for the application (which can create issues since by default is as long as the Kubernetes one). More info in the [Spring Boot docs](https://docs.spring.io/spring-boot/docs/2.7.6/reference/html/web.html#web.graceful-shutdown).

**Expected behavior**

I would expect Spring Boot to enable the graceful shutdown feature and rely on a grace period of 24 seconds, as configured by the convention (Kubernetes grace period * 0.8). However, since the property used doesn't exist in Spring Boot, the configuration is never applied.

**Steps to reproduce the bug**

Apply the conventions to a Spring Boot workload.

**Version** (Tanzu Application Platform, K8s the controller is installed on)

From what I can see from the [docs](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-spring-boot-conventions-reference-CONVENTIONS.html#spring-boot-graceful-shut-down-convention-2), the grace period bug also affects all versions of Tanzu Application Platform, whereas the graceful shutdown feature should be enabled correctly.

**Environment where the bug was observed (cloud, OS, etc)**

Not relevant.

**Relevant Debug Output (Logs, etc)**

**Expected**

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  ...
spec:
  template:
    metadata:
      annotations:
        ...
        conventions.carto.run/applied-conventions: |-
          ...
          spring-boot-convention/spring-boot-graceful-shutdown
          ...
      labels:
        ...
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.lifecycle.timeout-per-shutdown-phase=24s -Dserver.shutdown=graceful
```

**Actual**

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  ...
spec:
  template:
    metadata:
      annotations:
        ...
        conventions.carto.run/applied-conventions: |-
          ...
          spring-boot-convention/spring-boot-graceful-shutdown
          ...
      labels:
        ...
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.shutdown.grace-period=24s
```
